/*
SimuladorSO.java
Single-file Java Swing application for IntelliJ that simulates a simple "operating system" window
with several options and records every action in an Oracle 19c database.

Instrucciones rápidas:
1) Añade el driver de Oracle (ojdbc11.jar) al classpath / module dependencies en IntelliJ.
   - Descargar ojdbc11.jar (Oracle JDBC) y añadirlo en File > Project Structure > Modules > Dependencies.
2) Crear la tabla SQL en tu schema Oracle:

   CREATE TABLE so_actions (
       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       action_ts TIMESTAMP DEFAULT SYSTIMESTAMP,
       action_type VARCHAR2(100),
       details VARCHAR2(4000)
   );

3) Actualiza las constantes DB_URL, DB_USER, DB_PASS en la clase DBManager con tus valores:
   DB_URL ejemplo: "jdbc:oracle:thin:@//miHost:1521/miServicio"

4) Ejecuta esta clase como aplicación Java (ejecutar SimuladorSO.main).

Funcionalidad:
 - Ventana principal tipo "escritorio" con botones/menú: Abrir Programa, Listar Procesos, Crear Archivo, Borrar Archivo, Mostrar Historial (desde DB), Apagar
 - Cada acción se registra en la tabla so_actions
 - Historial se carga desde Oracle y se muestra en una JTable
 - Operaciones de ejemplo (simuladas) muestran diálogos y guardan detalles en la base

Notas de seguridad:
 - Este ejemplo usa credenciales en texto; en producción usa un store seguro o conexiones via datasource.
 - Manejo de excepciones simplificado para fines educativos.

 */
//TIP To <b>Run</b> code, press <shortcut actionId="Run"/> or
// click the <icon src="AllIcons.Actions.Execute"/> icon in the gutter.
public class SimuladorSO {
    public static void main(String[] args) {
        //TIP Press <shortcut actionId="ShowIntentionActions"/> with your caret at the highlighted text
        // to see how IntelliJ IDEA suggests fixing it.
        System.out.printf("Hello and welcome!");

        for (int i = 1; i <= 5; i++) {
            //TIP Press <shortcut actionId="Debug"/> to start debugging your code. We have set one <icon src="AllIcons.Debugger.Db_set_breakpoint"/> breakpoint
            // for you, but you can always add more by pressing <shortcut actionId="ToggleLineBreakpoint"/>.
            System.out.println("i = " + i);
        }
    }
}